"""E2E: vistas de lista, selección múltipla, pegar varias coplas, aliñamento de íncipits."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "harness"))
from common import APP, DB, OUT, sql, Client, SAMPLE_PDF
import urllib.request
from playwright.sync_api import sync_playwright
import shoot_lib as S
def handler(route):
    return route.continue_() if route.request.url.startswith(APP) else S.base_handle(route)
FAILS=[]
def ok(l,c,x=""):
    print(("PASS " if c else "FAIL ")+l,x)
    if not c: FAILS.append(l)
errs=[]
with sync_playwright() as p:
    b=p.chromium.launch()
    def page(vp):
        pg=b.new_page(viewport=vp); pg.route("**/*",handler)
        pg.on("pageerror",lambda e:errs.append(str(e)))
        urllib.request.urlopen("http://127.0.0.1:9911/set?sub=g-adm&email=folear3@gmail.com&name=Admin").read()
        pg.goto(APP+"/api/auth/google?next=/"); pg.wait_for_selector("#global-loading[hidden]",state="attached"); pg.wait_for_timeout(2500)
        return pg
    pg=page({"width":1440,"height":900})
    pg.click('.sidebar [data-view="coplas"]'); pg.wait_for_timeout(600)
    pg.click('[data-copla-view="incipits"]'); pg.wait_for_timeout(500)
    xs=pg.evaluate("[...document.querySelectorAll('.incipit-row .incipit-place')].slice(0,12).map(e=>Math.round(e.getBoundingClientRect().left))")
    ok("incipit place aligned", len(set(xs))==1, xs)
    cols=pg.evaluate("[...new Set([...document.querySelectorAll('.incipit-place .level-text')].slice(0,40).map(e=>getComputedStyle(e).color))]")
    ok("level colors differ", len(cols)>=2, cols)
    pg.screenshot(path=str(OUT/"t24-incipits.png"))
    # select mode
    pg.click("#toggleCoplaSelect"); pg.wait_for_timeout(500)
    ok("dock visible", pg.locator(".batch-dock").count()==1)
    xs=pg.evaluate("[...document.querySelectorAll('.incipit-row .incipit-place')].slice(0,12).map(e=>Math.round(e.getBoundingClientRect().left))")
    ok("aligned in select mode", len(set(xs))==1, xs)
    rows=pg.locator(".incipit-row")
    rows.nth(1).click(); pg.wait_for_timeout(300)
    ok("1 selected", pg.locator(".incipit-row.is-selected").count()==1 and "1" in pg.locator(".batch-dock-count b").inner_text())
    pg.locator(".incipit-row").nth(5).click(modifiers=["Shift"]); pg.wait_for_timeout(300)
    ok("shift range = 5", pg.locator(".incipit-row.is-selected").count()==5, pg.locator(".incipit-row.is-selected").count())
    pg.locator(".incipit-row .select-check").nth(3).click(); pg.wait_for_timeout(300)
    ok("checkbox deselect", pg.locator(".incipit-row.is-selected").count()==4)
    pg.screenshot(path=str(OUT/"t24-select-incipits.png"))
    box=pg.locator(".batch-dock").bounding_box(); ok("dock sticks to viewport bottom", box and box["y"]+box["height"]<=900 and box["y"]>600, box)
    pg.click("#batchSelectAllVisible"); pg.wait_for_timeout(300)
    ok("select all", pg.locator(".batch-dock-count b").inner_text()=="156")
    pg.click("#batchClearSelection"); pg.wait_for_timeout(300)
    ok("clear", pg.locator(".batch-dock-count b").inner_text()=="0" and pg.locator("#openBatchAssign").is_disabled())
    pg.keyboard.press("Escape"); pg.wait_for_timeout(300)
    ok("escape exits", pg.locator(".batch-dock").count()==0)
    pg.click("#toggleCoplaSelect"); pg.click('[data-copla-view="list"]'); pg.wait_for_timeout(500)
    pg.locator(".gallery-card.as-list").nth(0).click(position={"x":300,"y":60}); pg.wait_for_timeout(300)
    pg.screenshot(path=str(OUT/"t24-select-list.png"))
    pg.click("#batchExit"); pg.wait_for_timeout(300)
    pg.screenshot(path=str(OUT/"t24-list.png"))
    pg.click('[data-copla-view="gallery"]'); pg.click("#toggleCoplaSelect"); pg.locator(".gallery-card").nth(1).click(position={"x":100,"y":100}); pg.wait_for_timeout(400)
    pg.screenshot(path=str(OUT/"t24-select-gallery.png"))
    # paste
    pg.click('#view-coplas [data-view="submit"]'); pg.wait_for_timeout(700)
    pg.evaluate("document.querySelector('.paste-panel').open=true")
    pg.fill("#pasteBlock","Primeira copla\nsegundo verso\n\n>Volta da copla\nsegundo<\n\nA terriña de Almofrei\nxa non vexo"); pg.wait_for_timeout(300)
    ok("paste preview 3", pg.locator(".paste-item").count()==3 and "3 coplas" in pg.locator("#pasteSummary").inner_text(), pg.locator("#pasteSummary").inner_text())
    ok("volta count", "1 volta" in pg.locator("#pasteSummary").inner_text())
    pg.click('[data-paste-volta="0"]'); pg.wait_for_timeout(200)
    ok("toggle volta -> 2", "2 voltas" in pg.locator("#pasteSummary").inner_text() and pg.input_value("#pasteBlock").startswith(">Primeira"))
    pg.click("#pasteCheckDupes"); pg.wait_for_timeout(500)
    print("dupes:", pg.locator(".paste-dupe").count(), pg.locator("#pasteBlockFeedback").inner_text())
    pg.click('[data-paste-remove="1"]'); pg.wait_for_timeout(200)
    ok("remove -> 2", pg.locator(".paste-item").count()==2)
    pg.screenshot(path=str(OUT/"t24-paste.png"))
    pg.click("#parsePasteBlock"); pg.wait_for_timeout(800)
    ok("queued 2", pg.locator(".submit-batch-item").count()==2 and "Engadidas 2" in pg.locator("#pasteBlockFeedback").inner_text(), pg.locator(".submit-batch-item").count())
    ok("textarea cleared", pg.input_value("#pasteBlock")=="")
    pg.screenshot(path=str(OUT/"t24-paste-after.png"))
    # media / melodies
    for v,sel,attr in (("media","#mediaList","data-media-view"),("melodies","#melodiesList","data-melody-view")):
        pg.click(f'.sidebar [data-view="{v}"]'); pg.wait_for_timeout(800)
        pg.click(f'[{attr}="rows"]'); pg.wait_for_timeout(500)
        pg.screenshot(path=str(OUT/f"t24-{v}-rows.png"))
        n=pg.locator(f"{sel} > article").count(); ok(f"{v} rows", n>=1, n)
        pg.click(f'[{attr}="grid"]'); pg.wait_for_timeout(300)
        ok(f"{v} back to grid", pg.locator(f"{sel} > article.{'media-card' if v=='media' else 'melody-card'}").count()>=1)
        pg.click(f'[{attr}="rows"]')
    # persistencia
    pg.reload(); pg.wait_for_selector("#global-loading[hidden]",state="attached"); pg.wait_for_timeout(2000)
    pg.click('.sidebar [data-view="media"]'); pg.wait_for_timeout(600)
    ok("pref persisted", pg.locator("#mediaList.media-rows").count()==1)
    pg.close()
    # mobile
    pg=page({"width":390,"height":844})
    pg.click('.mobile-nav [data-view="coplas"]'); pg.wait_for_timeout(600)
    pg.click('[data-copla-view="incipits"]'); pg.wait_for_timeout(400)
    pg.screenshot(path=str(OUT/"t24-m-incipits.png"))
    pg.click("#toggleCoplaSelect"); pg.locator(".incipit-row").nth(2).click(); pg.wait_for_timeout(400)
    pg.screenshot(path=str(OUT/"t24-m-select.png"))
    ok("m no overflow", pg.evaluate("document.documentElement.scrollWidth<=innerWidth+1"))
    pg.click("#batchExit")
    pg.click('.mobile-nav [data-mobile-explore]'); pg.click('#mobileExploreMenu [data-view="media"]'); pg.wait_for_timeout(700)
    pg.click('[data-media-view="rows"]'); pg.wait_for_timeout(500)
    pg.screenshot(path=str(OUT/"t24-m-media.png"))
    ok("m media no overflow", pg.evaluate("document.documentElement.scrollWidth<=innerWidth+1"))
    pg.click('.mobile-nav [data-mobile-explore]'); pg.click('#mobileExploreMenu [data-view="melodies"]'); pg.wait_for_timeout(700)
    pg.click('[data-melody-view="rows"]'); pg.wait_for_timeout(500)
    pg.screenshot(path=str(OUT/"t24-m-melodies.png"))
    pg.close(); b.close()
print("ERRS",errs); print("FAILS",FAILS)
